http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  fast-api:
    host: localhost
    paths: ['/fast-api','/fast-api/*']
serviceEndpoints:
  fast-api:
   url: 'http://loadbalancer/fast-api/'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - fast-api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: fast-api
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false


